### ISSUE TITLE
Unable to export video

### ISSUE THREAD

**Issue by justingolden21** [jerryliuoft/SilenceRemover#1]
Hi, I love your tool! Unfortunately, it's not working for me. I get this in the console

```
Uncaught (in promise) Error: ffmpeg.FS('readFile', 'out.mp4') error. Check if the path exists
    at Object.I [as FS] (index-0e8b7cc3.js:128:4996)
    at HTMLButtonElement.v [as $$click] (index-0e8b7cc3.js:243:2863)
```

Thanks! :)

**Comment by jerryliuoft** [comment]
Thanks!!!

I think if you close your browser and try it again it should solve it. 

If not can you tell me what browser are you using on what device? I’ll try and see if I can reproduce it. It’s basically saying it can’t find the file. Which is weird unless your file is too big

**Comment by jerryliuoft** [comment]
This should be fixed on the latest version
