### ISSUE TITLE
Warn user before overwriting manual changes 

### ISSUE THREAD

**Issue by jfhc** [jerryliuoft/SilenceRemover#5]
I made some tweaks to the highlighted regions manually, then without thinking changed a parameter and clicked analyse , which of course undid the changes I had made. It might be helpful to have a pop up when someone does that if they have made changes warning them they would be lost?

**Comment by jerryliuoft** [comment]
Ah that's a good point. Let me think about how to fix that. I might not do pop up because it gets annoying when I click the analyze multiple times

**Comment by jerryliuoft** [comment]
It should be fixed now
