### ISSUE TITLE
issues with importing XMLs into Davinci Resolve

### ISSUE THREAD

**Issue by AuburnWisp** [jerryliuoft/SilenceRemover#6]
I am having issues with importing XMLs into DaVinci Resolve, whenever I do so I get the error "Skipping item because of invalid in frame"

**Comment by jerryliuoft** [comment]
Did you ever get xml export to work? Like with a different video?
It sounds like the app wasn't able to figure out what frame rate your video is in.

If you can like clip me a short video I can take a look. It must be something about how it is encoded or a format I've not tested with

**Comment by jerryliuoft** [comment]
Actually give this one more shot, I might've fixed the issue
