### ISSUE TITLE
[FEATURE] Ability to pause an export is needed

### ISSUE THREAD

**Issue by AmpereBEEP** [jerryliuoft/SilenceRemover#9]
It would be extremely useful to be able to pause an export if the incorrect settings have been used as I would need to wait for the video to fully export before I can change the settings. For example, I accidentally started an export after editing a video, and by clicking export on without selecting multithreading it is exporting at an extremely slow rate. There is no way to pause this process nor is there a way for me to export the XML timeline during this either.

**Comment by jerryliuoft** [comment]
Oh good point! Thanks for the feedback. I'll start working on this.

**Comment by jerryliuoft** [comment]
It should now automatically save your previous settings and reapply them. So you don't have to worry about refreshing the page and lose your previous changes.
Also its by default now multi thread so no more need to toggle
Thanks for the feature request!
